# Generated by Django 4.1.1 on 2022-10-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='タイトル')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='説明')),
                ('content', models.TextField(verbose_name='テキスト')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
