# Generated by Django 4.1.1 on 2022-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
