# Generated by Django 4.1.1 on 2022-10-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_alter_article_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
