# Generated by Django 4.1.1 on 2022-10-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bbs.category', verbose_name='カテゴリー'),
            preserve_default=False,
        ),
    ]
