# Generated by Django 4.1.1 on 2022-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, to='bbs.article', verbose_name='関連'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='bbs.tag', verbose_name='タグ'),
        ),
    ]
