# Generated by Django 4.1.1 on 2022-10-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_article_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
    ]
