# Generated by Django 4.1.1 on 2022-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_remove_article_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='説明'),
        ),
    ]
