# Generated by Django 4.1.1 on 2022-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_tag_article_relation_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='relation',
            field=models.ManyToManyField(blank=True, to='bbs.article', verbose_name='関連'),
        ),
    ]
