# Generated by Django 4.1.1 on 2022-11-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_remove_article_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_body',
            field=models.TextField(default=1, verbose_name='プレーンテキスト'),
            preserve_default=False,
        ),
    ]
